draw_set_font(f_vhs)
draw_set_color(c_aqua)
draw_text(x + 30, y - 120, "Mikita Slabysh")
draw_text(x - 320, y - 120, "Vy Do")
draw_text(x - 320, y - 60, "Evan Herring")
draw_text(x - 320, y + 120, "Timothy Aucoin")
draw_text(x - 320, y + 180, "Cameron Moore")
draw_set_font(f_vhs_medium)
draw_set_color(c_fuchsia)
draw_text(x - 300 , y - 300, "Tsunami Surfers")

