instance_create_layer(x + 440, y - 330, "SettingsTop", o_close_button)
instance_create_layer(x + 400, y - 177, "SettingsTop", o_add_speed_button)
instance_create_layer(x + 400, y - 74, "SettingsTop", o_add_gas_button)
instance_create_layer(x + 400, y + 30, "SettingsTop", o_add_health_button)
instance_create_layer(x + 70, y + 190, "SettingsTop", o_color_black_button)
instance_create_layer(x + 140, y + 190, "SettingsTop", o_color_red_button)
instance_create_layer(x + 210, y + 190, "SettingsTop", o_color_white_button)