draw_set_font(f_vhs_big)
draw_set_color(c_fuchsia)
draw_text(x - 400, y - 420, "Statistics")
draw_set_font(f_vhs)
draw_set_color(c_aqua)
draw_text(x - 420,y - 280, "Cash Earned: ")
draw_set_color(c_fuchsia)
draw_text(x + 280,y - 280, "$" + string(global.cash_earned))
draw_set_color(c_aqua)
draw_text(x - 420,y - 220, "Jobs done: ")
draw_set_color(c_fuchsia)
draw_text(x + 280,y - 220, string(global.jobs_done))
draw_set_color(c_aqua)
draw_text(x - 420,y - 160, "Streets driven: ")
draw_set_color(c_fuchsia)
draw_text(x + 280,y - 160, string(global.streets_driven))
draw_set_color(c_aqua)
draw_text(x - 420,y - 100, "Cops destroyed: ")
draw_set_color(c_fuchsia)
draw_text(x + 280,y - 100, string(global.cops_kills))
draw_set_color(c_aqua)
draw_text(x - 420,y - 40, "People's days ruined: ")
draw_set_color(c_fuchsia)
draw_text(x + 280,y - 40, string(global.civ_kills))
draw_set_color(c_aqua)
draw_text(x - 420,y + 20, "Props annihilated:  ")
draw_set_color(c_fuchsia)
draw_text(x + 280,y + 20, string(global.prop_kills))
draw_set_color(c_aqua)
draw_text(x - 420,y + 80, "Bullets fired:  ")
draw_set_color(c_fuchsia)
draw_text(x + 280,y + 80, string(global.bullets_fired))
draw_set_color(c_aqua)
draw_text(x - 420,y + 140, "Gas used: ")
draw_set_color(c_fuchsia)
draw_text(x + 280,y + 140, string(global.gas_used) + " L")
draw_set_color(c_aqua)
draw_text(x - 420,y + 200, "Money spent:  ")
draw_set_color(c_fuchsia)
draw_text(x + 280,y + 200, "$" + string(global.money_spent))
draw_set_color(c_aqua)
draw_text(x - 420,y + 260, "Biggest score:  ")
draw_set_color(c_fuchsia)
draw_text(x + 280,y + 260, "$" + string(global.money_highscore))


